name: Feature request
description: I want to request a new feature, or propose a change to an existing feature.
title: "[FEATURE REQUEST]: "
labels: ["enhancement"]
assignees:
  - martijnvankekem
body:
  - type: markdown
    attributes:
      value: |
        Thank your for taking the time to help improve Sticky Toolkit! In order to help you as best as possible, please fill in the information below.
  - type: textarea
    id: request
    attributes:
      label: Description of your idea
      description: Detailed description of your new idea. What are your requirements?
      placeholder: Tell us your best idea!
    validations:
      required: true
  - type: checkboxes
    id: product
    attributes:
      label: Product
      description: What product are you suggestion this feature for? Select all options that apply.
      options:
        - label: Sticky Toolkit for Apple WatchOS
          required: false
        - label: Sticky Toolkit for Android WearOS (all android watches + Samsung Galaxy Watch 4)
          required: false
        - label: Sticky Toolkit for Tizen OS (all Galaxy watches except prior to thhe Galaxy Watch 4)
          required: false
  - type: textarea
    id: info
    attributes:
      label: Other relevant info
      description: If there is anything else to mention that is relevant to this request, please do so below.
